site_name: Documentation
site_description: Documentation for the Infobaleen Platform
theme:
    name: material
    palette:
        primary: deep purple
    logo: assets/logo.png
    favicon: assets/favicon.ico
    custom_dir: overrides
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
extra_css:
  - custom/extra.css
nav:
    - Home: index.md

    - Analytics:
        - Dashboards: Platform/Analytics/Dashboards.md
        - Customer Insights: Platform/Analytics/Customer-Insights.md
    - Segmentations:
        - Auto-targeting: Platform/Segmentations/Auto-targeting.md
        - Clustering: Platform/Segmentations/Clustering.md
    - Recommendations:
        - Platform/Recommendations/Recommendations.md
        - Platform/Recommendations/Settings.md
        - Platform/Recommendations/Front page.md
        - Platform/Recommendations/Data available in recommendations.md
        - Platform/Recommendations/Recommendations in emails.md
        - Platform/Recommendations/Infobaleen recommended recommendation profiles.md
    - Menu:
        - Account:
            - API Keys: Platform/Menu/Account/API-Keys.md
            - Logout: Platform/Menu/Account/Logout.md
            - Users: Platform/Menu/Account/Users.md
        - Admin:
            - Clear CH chache: Platform/Menu/Admin/Clear-CH-chache.md
            - Configuration: Platform/Menu/Admin/Configuration.md
            - Connections: Platform/Menu/Admin/Connections.md
            - Events: Platform/Menu/Admin/Events.md
            - Secrets: Platform/Menu/Admin/Secrets.md
        - Documentation:
            - Agent: Platform/Menu/Documentation/Agent.md
            - Recommendations API: Platform/Menu/Documentation/Recommendations.md
            - New Issue: Platform/Menu/Documentation/New-Issue.md
        - Manage Data:
            - Data Models: Platform/Menu/Manage Data/Data-Models.md
            - Import Files: Platform/Menu/Manage Data/Import-Files.md
            - Results: Platform/Menu/Manage Data/Results.md
            - Sources: Platform/Menu/Manage Data/Sources.md
        - Model:
            - Interactions: Platform/Menu/Model/Interactions.md
            - Overview: Platform/Menu/Model/Overview.md
            - Products: Platform/Menu/Model/Products.md
            - Users: Platform/Menu/Model/Users.md
        - Other: Platform/Menu/Other/Overlaps.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format