site_name: Documentation
site_description: Documentation for the Infobaleen Platform
theme:
    name: material
    font:
        text: Roboto
    # palette:

    #     # Palette toggle for light mode
    #     - scheme: default
    #       primary: deep purple
    #       accent: deep purple
    #       toggle:
    #         icon: material/brightness-7 
    #         name: Switch to dark mode

    #     # Palette toggle for dark mode
    #     - scheme: slate
    #       toggle:
    #         icon: material/brightness-auto
    #         name: Switch to light mode
    logo: assets/logo.png
    favicon: assets/favicon.ico
    custom_dir: overrides
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
extra_javascript:
  - https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap
extra_css:
  - stylesheets/extra.css
nav:
    - Home: index.md
    - Analytics:
        - Dashboards: Platform/Analytics/Dashboards.md
        - Customer Insights: Platform/Analytics/Customer-Insights.md
    - Segmentations:
        - Overview: Platform/Segmentations/Segmentation_overview.md
        - Auto-targeting: Platform/Segmentations/Auto-targeting.md
        - Clustering: Platform/Segmentations/Clustering.md
    - Recommendations:
        - Platform/Recommendations/Overview.md
        - Platform/Recommendations/Example Use Cases.md
        - Platform/Recommendations/Settings.md
       # - Platform/Recommendations/Front page.md
       # - Platform/Recommendations/Data available in recommendations.md
       # - Platform/Recommendations/Recommendations in emails.md
       # - Platform/Recommendations/Infobaleen recommended recommendation profiles.md
    - Configure the platform:
        - Model:
            - Overview: Platform/Menu/Model/Overview.md
            - Interactions: Platform/Menu/Model/Interactions.md
            - Products: Platform/Menu/Model/Products.md
            - Users: Platform/Menu/Model/Users.md
        - Manage Data:
            - Data Models: Platform/Menu/Manage Data/Data-Models.md
            - Import Files: Platform/Menu/Manage Data/Import-Files.md
            - Results: Platform/Menu/Manage Data/Results.md
            - Sources: Platform/Menu/Manage Data/Sources.md
        - Documentation:
            - Agent: Platform/Menu/Documentation/Agent.md
            - Recommendations API: Platform/Menu/Documentation/Recommendations.md
            - New Issue: Platform/Menu/Documentation/New-Issue.md
        - Account:
            - API Keys: Platform/Menu/Account/API-Keys.md
            - Logout: Platform/Menu/Account/Logout.md
            - Users: Platform/Menu/Account/Users.md
        # - Admin:
        #     - Clear CH chache: Platform/Menu/Admin/Clear-CH-chache.md
        #     - Configuration: Platform/Menu/Admin/Configuration.md
        #     - Connections: Platform/Menu/Admin/Connections.md
        #     - Events: Platform/Menu/Admin/Events.md
        #     - Secrets: Platform/Menu/Admin/Secrets.md

        #- Other: Platform/Menu/Other/Overlaps.md
    - Other:
        - Data Specification: Other/Data-Specification.md

markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format